# Generated by Django 5.0.7 on 2024-09-04 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="status",
        ),
    ]
