name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder step
        run: echo "CD workflow placeholder"
